### ISSUE TITLE
Checklist migración entorno

### ISSUE THREAD

**Issue by rcastellor1** [rcastellor1/actions#2]
En esta issue mantenemos un listado de temas que tenemos que migrar

- [ ] Migración DB
- [ ] Migración function sisu-api a WrapperIn
- [ ] Cambio de integración wrapper on-pre
- [ ] Replicador AWS Azure
- [ ] Migración function sisu-sga-event Wrapper
- [ ] Migración function sisu-event a Wrapper
